#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         BBDB-Export
version:      0.012
version_from: lib/BBDB/Export.pm
installdirs:  site
requires:
    Term::ANSIColor:               0
    Text::vFile::asData:           0
    BBDB:                          0
    Test::More:                    0
    Pod::Usage:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
